### PR TITLE
update hunspell version to 1.7.2

### PR DESCRIPTION
**Pull request by vitaliy-aksyonov**

### CODE REVIEW

**Review by dukelsky — CHANGES_REQUESTED** [review]
Please resolve Codacy issues. Hopefully, you have registered there. Also, please stick to the style of the existing code. It should be:
```
FileMgr::~FileMgr()
{
    delete hin;
}
```
and not
```
FileMgr::~FileMgr() {
  delete hin;
}
```
Indent is 4 spaces, and not 2.

**Comment by vitaliy-aksyonov** [comment]
> Please resolve Codacy issues. Hopefully, you have registered there. Also, please stick to the style of the existing code. It should be:
> 
> ```
> FileMgr::~FileMgr()
> {
>     delete hin;
> }
> ```
> 
> and not
> 
> ```
> FileMgr::~FileMgr() {
>   delete hin;
> }
> ```
> 
> Indent is 4 spaces, and not 2.

That's not my code. I'm not going to spend more time just to make this library look like part of golded.
Old hunspell library was exactly like this version.

**Comment by dukelsky** [comment]
> > Please resolve Codacy issues. Hopefully, you have registered there. Also, please stick to the style of the existing code. It should be:
> > ```
> > FileMgr::~FileMgr()
> > {
> >     delete hin;
> > }
> > ```
> > 
> > 
> > and not
> > ```
> > FileMgr::~FileMgr() {
> >   delete hin;
> > }
> > ```
> > 
> > 
> > Indent is 4 spaces, and not 2.
> 
> That's not my code. I'm not going to spend more time just to make this library look like part of golded. Old hunspell library was exactly like this version.

Ah, sorry, I did not notice it was not your code. And what about the issues in the code? Is it better not to pay attention to them?

**Comment by vitaliy-aksyonov** [comment]
Most of them are strcpy like functions. Sure it's better to fix them and maybe even send those patches to upstream, but it will take some time. Older hunspell version had same approaches and I believe new one is not worse.
Also it's better to leave it this way because new merges from upstream will be much easier. I had to spend almost whole day just to make it work in MSVC 6. You know that it's not even C++98. )

**Comment by dukelsky** [comment]
> Most of them are strcpy like functions. Sure it's better to fix them and maybe even send those patches to upstream, but it will take some time. Older hunspell version had same approaches and I believe new one is not worse. Also it's better to leave it this way because new merges from upstream will be much easier. I had to spend almost whole day just to make it work in MSVC 6. You know that it's not even C++98. )

OK.

**Review by dukelsky — APPROVED** [review]

**Comment by dukelsky** [comment]
I did not delete the branch. Maybe you will need it if you have time to fix the issues and send them to upstream. If you don't need it, then delete it.

**Comment by vitaliy-aksyonov** [comment]
Sounds good. It's convenient to have codacity inspections. Let's leave that branch. I'll try to find some time to work on those issues.

**Pull request merged**
