### PR TITLE
fix loading multiple spellchecker dictionaries

### PR DESCRIPTION
**Pull request by vitaliy-aksyonov**
strtok() is used down the stack in schecker.Load() and destroys internal state.
Only first dictionary was loaded because of this.

### CODE REVIEW

**Review by spanevin — COMMENTED** [review]
Don't we want to update version number?

**Comment by spanevin** [comment]
> strtok() is used down the stack in schecker.Load() and destroys internal state. Only first dictionary was loaded because of this.

Is it about user dictionaries or system dictionaries? System dictionaries worked well, AFAIR...

**Comment by vitaliy-aksyonov** [comment]
> > strtok() is used down the stack in schecker.Load() and destroys internal state. Only first dictionary was loaded because of this.
> 
> Is it about user dictionaries or system dictionaries? System dictionaries worked well, AFAIR...

If you use multiple dictionaries in SCheckerDefLang, only first is loaded.

For example 'SCheckerDefLang ru_RU en_US'. English dictionary is not loaded and have to be activated manually in spellchecker menu.

**Comment by spanevin** [comment]
> > > strtok() is used down the stack in schecker.Load() and destroys internal state. Only first dictionary was loaded because of this.
> > 
> > 
> > Is it about user dictionaries or system dictionaries? System dictionaries worked well, AFAIR...
> 
> If you use multiple dictionaries in SCheckerDefLang, only first is loaded.
> 
> For example 'SCheckerDefLang ru_RU en_US'. English dictionary is not loaded and have to be activated manually in spellchecker menu.

How does it work for me without this fix? (yes it does!)

**Comment by vitaliy-aksyonov** [comment]
> > > > strtok() is used down the stack in schecker.Load() and destroys internal state. Only first dictionary was loaded because of this.
> > > 
> > > 
> > > Is it about user dictionaries or system dictionaries? System dictionaries worked well, AFAIR...
> > 
> > 
> > If you use multiple dictionaries in SCheckerDefLang, only first is loaded.
> > For example 'SCheckerDefLang ru_RU en_US'. English dictionary is not loaded and have to be activated manually in spellchecker menu.
> 
> How does it work for me without this fix? (yes it does!)

Are you sure that second dictionary is working? For me it was not. Just the first.

strtok shall not be used the way it is used anyway because any other function call may use it too and will destroy internal state and other tokens won't be returned. I'll look at code later and let you know which function does it for me.

**Comment by vitaliy-aksyonov** [comment]
When spellchecker dictionary loaded, it calls LoadCharset, which calls strlword which uses strtok internally.

**Review by spanevin — APPROVED** [review]
I trust you that updated version works :) I just don't understand why old version works for me when it shouldn't :)

**Review by spanevin — APPROVED** [review]

**Pull request merged**
